src/try_django/blog/urls.py
from django.contrib import admin
from django.urls import path, re_path
from .views import (blog_post_detail_view, blog_post_list_view,
                    blog_post_create_view, blog_post_update_view, blog_post_delete_view)

urlpatterns = [
    path('', blog_post_list_view, name="blog_list"),
    path('<int:page>/', blog_post_list_view, name="blog_page"),
    path('<slug:title>/', blog_post_detail_view, name="blog_detail"),
    path('<slug:title>/edit/', blog_post_update_view, name="blog_update"),
    path('<slug:title>/delete/', blog_post_delete_view, name="blog_delete"),

    path('blog-new/', blog_post_create_view, name="blog_create"),

]

src/try_django/try_django/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, re_path, include
from .views import *
from blog.views import blog_post_create_view
from searches.views import search_view, tmp_view

from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap
from blog.sitemap import BlogPostSitemap

from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _


sitemaps = {
    'blogpostsitemap': BlogPostSitemap
}

urlpatterns = [
    url(r'^sitemap[.]xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    path('blog-new/', blog_post_create_view, name="blog_create"),
    path('blog-new/<slug:title>/', blog_post_create_view, name="blog_create"),
    #path('blog/', include('blog.urls')),

    #path('', home_page, name="home_page"),
    re_path(r'^about/$', about_page, name="about_page"),
    path('contact/', contact_page, name="contact_page"),
    path('example/', example_page, name="example_page"),

    path('search/', search_view, name="search_view"),
    path('search/<int:page>/', search_view, name="search_page"),


    path('accounts/', include('django.contrib.auth.urls'), name="accounts_page"),
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(#u'',
    url(r'^$', home_page, name='homepage'),
    path(r'blog/', include('blog.urls')),
    #todo: add blogpost urls
)


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/try_django/blog/models.py
from django.db import models
from django.conf import settings
# Create your models here.
from django.template.defaultfilters import slugify
from django.db.models.signals import pre_save
from django.utils import timezone
from django.db.models import Q

User = settings.AUTH_USER_MODEL


class BlogPostQuerySet(models.QuerySet):

    def published(self):
        now = timezone.now()
        return self.filter(publish_date__lte=now)

    def search(self, query):
        #return self.filter(content__contains=query)
        lookup = (Q(title__icontains=query) | Q(content__icontains=query) | Q(user__username__icontains=query))
        return self.filter(lookup)


class BlogPostManager(models.Manager):

    def published(self):
        #return self.get_queryset().published()
        now = timezone.now()
        return self.get_queryset().filter(publish_date__lte=now)

    def get_queryset(self):
        return BlogPostQuerySet(self.model, using=self._db)

    def search(self, query=None):
        if query is None:
            return self.get_queryset().none()
        return self.get_queryset().published().search(query)

    def superuser_search(self, query):
        if query is None:
            return BlogPost.objects.none()
        return self.get_queryset().search(query)



class BlogPost(models.Model):
    user = models.ForeignKey(User, default=1, null=True, on_delete=models.SET_NULL)  # user that created BlogPost
                                                                                    # by deleting set user to default
    image = models.ImageField(upload_to='image/', blank=True, null=True)
    # todo: validation title - cannot start with number
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    content = models.TextField(null=True, blank=True)
    publish_date = models.DateTimeField(auto_now=False, auto_now_add=False, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    objects = BlogPostManager()

    class Meta:
        ordering = ['-publish_date', '-last_updated', '-timestamp']

    def get_slug(self):
        return slugify(self.title)

    def save(self, *args, **kwargs):
        self.slug = self.get_slug()
        if len(BlogPost.objects.filter(slug=self.slug)) >= 1:
            print("cannot save, unique slug, title already exist, ...")
            # raise exception or do something
            # return
        super(BlogPost, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return "/blog/{}/".format(self.slug)

    def get_edit_url(self):
        return "/blog/{}/edit/".format(self.slug)

    def get_delete_url(self):
        return "/blog/{}/delete".format(self.slug)

    def __str__(self):
        return "{} ({})".format(self.slug, self.id)

    def is_publish_recently(self) -> bool:
        if self.publish_date is None:
            return False
        return self.publish_date <= timezone.now()


def do_whatever_you_need_with(bp: BlogPost):
    print("hello pre_save Blog Post " + str(bp.id) + " " + bp.title)
    bp.slug = slugify(bp.title)


def extraInitForMyModel(**kwargs):
   instance = kwargs.get('instance')
   do_whatever_you_need_with(instance)

# pre_save.connect(extraInitForMyModel, BlogPost)


from django.contrib.auth.models import User
from django.db import models
from  django.db.models.signals import post_save


class UserProfile(models.Model):
    user   = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='image/users_avatars', default="image/users_avatars/user.png")


def create_user_profile(sender, instance, created, **kwargs):
    if created:
       profile, created = UserProfile.objects.get_or_create(user=instance)

# This will create a userprofile each time a user is saved if it is created.
post_save.connect(create_user_profile, sender=User)


class Comment(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    blogpost = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    content = models.TextField()

    class Meta:
        ordering = ['timestamp']

src/try_django/blog/forms.py
from django import forms
from .models import BlogPost
from django.template.defaultfilters import slugify


class BlogPostForm(forms.Form):
    title = forms.CharField()
    slug = forms.SlugField()
    content = forms.CharField(widget=forms.Textarea)


class BlogPostModelForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ['title', 'image', 'content', 'publish_date']

    def clean_title(self):
        title = self.cleaned_data.get('title')
        slug_title = slugify(title)
        qs = BlogPost.objects.filter(slug=slug_title)
        if self.instance is not None:
            qs = qs.exclude(pk=self.instance.pk)
        if qs.exists():
            raise forms.ValidationError("Post with title '{}' already exists.".format(title))
        return title


class CommentForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea(attrs={'cols': 80, 'rows': 4}), label='')

src/try_django/blog/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from .models import BlogPost, Comment
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, get_list_or_404, redirect
from .forms import BlogPostModelForm, CommentForm
from django.utils import timezone
from django.db import IntegrityError
import math
# Create your views here.


def blog_post_list_view(request, *args, **kwargs):

    qs = BlogPost.objects.all().published()
    if request.user.is_superuser:
        qs = BlogPost.objects.all()
    elif request.user.is_authenticated:
        user_posts = BlogPost.objects.filter(user=request.user)
        qs = (qs | user_posts).distinct()

    # todo: user choice blog+post per page
    print(kwargs)
    per_page = 3
    page = 1  # pages counting from 1
    try:
        page = kwargs['page']
    except KeyError:
        page = 1

    number_of_blog_posts = len(qs)
    number_of_pages = math.ceil(number_of_blog_posts / per_page)
    ix_down = (page-1) * per_page
    ix_up = min(ix_down + per_page, number_of_blog_posts)
    if ix_down > number_of_blog_posts:
        raise Http404("Exceed number of blog_posts.")

    template_name = "blog/list.html"
    pages = generate_paginationbar_pages(number_of_pages, page)
    context = {"object_list": qs[ix_down: ix_up], "pages": pages, "page": page, "last_page": number_of_pages}

    return render(request, template_name, context)


#@login_required(login_url='/login')
@staff_member_required
def blog_post_create_view(request, *args, **kwargs):
    # create view
    template_name = "form.html"
    print('-------------------------------')
    print("files: ", request.FILES)
    print("request: ", request)

    try:
        title = kwargs['title']
    except KeyError:
        title = ""

    unsluged_title = unslugify(title)
    form = BlogPostModelForm(request.POST or None, request.FILES or None, initial={'title': unsluged_title})
    context = {"form": form}

    if form.is_valid():
        # to manipulate with form data
        obj = form.save(commit=False)
        obj.title = form.cleaned_data.get("title")
        obj.user = request.user
        obj.save()
        #obj = BlogPost.objects.create(**form.cleaned_data)
        form = BlogPostModelForm()
        context["save"] = True
        context["object"] = obj
        # todo: add message_list

    context["form"] = form
    return render(request, template_name, context)


def blog_post_detail_view(request, *args, **kwargs):

    try:
        obj = BlogPost.objects.get(slug=kwargs['title'])
    except BlogPost.DoesNotExist:
        return render(request, 'blog/create_new.html', {"obj_title": kwargs['title']})

    template_name = "blog/detail.html"
    context = {"object": obj}

    form = CommentForm(request.POST or None)
    context["comment_form"] = form

    if request.method == "POST":
        print(request)
        print(request.POST)

        if 'delete_yes' in request.POST:
            #print('I want to delete object ', obj.slug)
            obj_title = obj.slug
            obj.delete()
            return render(request, 'blog/create_new.html', {"obj_title": obj_title, "delete_yes": True})
        elif 'delete_cancel' in request.POST:
            #print('I do not want delete object ', obj.slug)
            return render(request, template_name, context)
        elif 'comment':
            if form.is_valid():
                Comment.objects.create(user=request.user, blogpost=obj, content=form.cleaned_data.get('content'))
                form = CommentForm()
                context["comment_form"] = form
                context["comment_save"] = True
                return render(request, template_name, context)

        return HttpResponseRedirect(obj.get_absolute_url())

    return render(request, template_name, context)


@staff_member_required
def blog_post_update_view(request, *args, **kwargs):

    obj = get_object_or_404(BlogPost, slug=kwargs['title'])
    form = BlogPostModelForm(request.POST or None, request.FILES or None, instance=obj)
    context = {}

    print(form.changed_data)
    print(form.is_valid())
    if form.is_valid() and form.changed_data != []:
        form.save()
        context["save"] = True
        if kwargs['title'] != obj.slug:
            return HttpResponseRedirect(obj.get_edit_url())

    template_name = "blog/form.html"
    context["form"] = form
    context["object"] = obj
    print(context)
    return render(request, template_name, context)


@staff_member_required
def blog_post_delete_view(request, *args, **kwargs):
    obj = get_object_or_404(BlogPost, slug=kwargs['title'])
    template_name = "blog/delete.html"
    context = {"object": obj}
    if request.method == "POST":
        print("request POST in delete")
        obj.delete()
        return blog_post_list_view(request, args, kwargs)
    return render(request, template_name, context)


def generate_paginationbar_pages(n: int, ix: int):
    " returns list of page numbers which displays in paginationbar"
    # maximum 11 pages(<li>) exclusive (Next, Previous) per web-page
    # ix - current page
    # -1 stands for <li>...</li>
    pages = [1, 2] + [-1] + [ix-2, ix-1, ix, ix+1, ix+2] + [-1] + [n-1, n]
    if n <= 11:
        return range(1, n+1)
    if ix <= 6:
        pages = [1, 2, 3, 4, 5, 6, 7, 8] + [-1] + [n-1, n]
    if n - ix <= 5:
        pages = [1, 2] + [-1] + [n-7, n-6, n-5, n-4, n-3, n-2, n-1, n]

    return pages



def unslugify(slug: str):
    tmp = slug.replace('-', ' ')
    return tmp.title()

src/try_django/blog/templates/blog/comment-inline.html
{% load static %}

<div class="card mb-2">
    <div class="card-body">

        <ul class="list-inline">
            <li class="list-inline-item">
                <img class="mr-3 img-circle" src="{% if not comment.user.userprofile.avatar.url %}{% static 'user.png' %}{% else %}{{ comment.user.userprofile.avatar.url }}{% endif %}" alt="img" width="30" height="30">
            </li>
            <li class="list-inline-item font-weight-bold">{{comment.user.username}}</li>
            <li class="list-inline-item text-muted">{{comment.timestamp}}</li>
        </ul>

        <p>{{comment.content}}</p>
    </div>
</div>

src/try_django/blog/templates/blog/create.html
{% extends "base.html" %}

{% block content %}
<h3>Create new blogpost</h3>
{% endblock %}

src/try_django/blog/templates/blog/create_new.html
{% extends 'base.html' %}

{% block content_b %}

    <div class="card">
        <div class="card-body">
            {% if delete_yes %}
                {% include 'blog/message_list.html' with action=2 blog_title=obj_title %}
            {% else %}
                {% include 'blog/message_list.html' with action=1 blog_title=obj_title %}
            {% endif %}
            <div>
                <a href="/blog-new/{{obj_title}}"><button class="btn btn-danger">Create new</button></a>
                <a href="/blog/1"><button class="btn btn-dark">Go back</button></a>
            </div>
        </div>
    </div>
{% endblock %}

src/try_django/blog/templates/blog/delete.html
{% extends "base.html" %}

{% block content_b %}
<div class="card">
    <div class="card-body">
    <p class="card-title">Are you sure you want to delete <span class="font-weight-bold">{{object.title}}</span>?</p>

<div>
    <form class="d-inline" method="post" action="{{object.get_absolute_url}}">{% csrf_token %}
        <button class="btn btn-danger" name="delete_yes">Yes</button>
    </form>

    <form class="d-inline" method="post" action="{{object.get_absolute_url}}">{% csrf_token %}
        <button class="btn btn-dark" name="delete_cancel">Cancel</button>
    </form>
</div>

    </div>
</div>
{% endblock %}

src/try_django/blog/templates/blog/detail.html
{% extends "base.html" %}


{% block content_b %}
<div class="row">
    <div class="col-12 col-8 mx-auto">
        {% if save %}
            {% include 'blog/message_list.html' with action=3 blog_title=obj_title %}
        {% elif comment_save %}
            {% include 'blog/message_list.html' with action=4 %}
        {% endif %}

        {% include 'blog/list-inline.html' with blog_post=object truncate=False detail=True form=comment_form %}
    </div>
</div>
{% endblock %}

{% block content_c %}
{% endblock %}

src/try_django/blog/templates/blog/form.html
{% extends "base.html" %}

{% block content_b %}


<div class="card">
    <div class="card-body">
        {% if save %}
            {% include 'blog/message_list.html' with action=3 blog_title=object.title %}
        {% endif %}
        <p class="card-title">Edit <span class="font-weight-bold">{{object.title}}</span>.</p>

        <div>
            <form class="d-inline" method="post" enctype="multipart/form-data">{% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-danger" type="submit" name="submit">Save</button>
            </form>

            <form class="d-inline" method="post" action="{{object.get_absolute_url}}">{% csrf_token %}
                <button class="btn btn-dark" name="edit_cancel">Cancel</button>
            </form>
        </div>

    </div>
</div>

{% endblock %}

src/try_django/blog/templates/blog/list-inline.html
<div class=" card mb-3
            {% if not blog_post.publish_date %}
                border border-danger
            {% elif not blog_post.is_publish_recently %}
                border border-warning
            {% endif %}
            "
>
    <div class="card-body">
        <h5 class="card-title"><a href="{{blog_post.get_absolute_url}}">{{blog_post.title}}</a></h5>

        <p class="text-muted">
                <span class="font-weight-bold" >{{ blog_post.user}}</span>
                {% if not blog_post.publish_date %}
                    <span >Not yet published.</span>
                {% elif not blog_post.is_publish_recently %}
                    <span>Will be published on {{blog_post.publish_date}}.</span>
                {% else %}
                    <span>{{blog_post.publish_date}}</span>
                {% endif %}
        </p>

        {% if request.user == object.user or request.user.is_superuser %}
            {% include 'blog/toolbar.html' %}
        {% endif %}

        {% if blog_post.image %}
            <img src="{{ blog_post.image.url }}" alt="blog_post image" class="card-img-top my-1" />
        {% endif %}

        <p class="card-text">

            {% if truncate %}
                {{blog_post.content|linebreaks|truncatewords:150}}
            {% else %}
                {{blog_post.content|linebreaks}}
            {% endif %}

            {% if not detail %}
                <a href="{{blog_post.get_absolute_url}}">View</a>
            {% else %}

                <div class="border-top">
                    <h4 class="mt-3"> Comment section </h4>
                    {% for cmt in blog_post.comment_set.all %}
                        {% include 'blog/comment-inline.html' with comment=cmt %}
                    {% endfor %}
                </div>

                {% if request.user.is_authenticated %}
                <div class="card mb-2">
                    <div class="card-body">
                        <form method="post"> {% csrf_token %}
                            {{ form.as_p }}
                        <button class="btn btn-danger" type="submit" name="comment">add comment</button>
                        </form>
                    </div>
                </div>
                {% else %}
                    <p>You need to be logged in to comment.</p>
                {% endif %}
            {% endif %}
        </p>
    </div>
</div>

src/try_django/blog/templates/blog/list.html
{% extends "base.html" %}



{% block content_b %}

    {% if msg_list %}
        {% include 'blog/message_list.html' with msg=msg_list %}
    {% endif %}

    <div class="row">
    <div class="col-12 col-8 mx-auto">
        {% for object in object_list %}
            {% include 'blog/list-inline.html' with blog_post=object truncate=True detail=False %}
        {% endfor %}
    </div>
    </div>

    {% include 'blog/paginationbar.html' with active_page=i %}
{% endblock %}

{% block content_c %}
{% endblock %}

src/try_django/blog/templates/blog/message_list.html
<div role="alert">
    {% if action == 1 %}
    <p class="alert alert-warning">
        Blog post <span class="font-weight-bold">{{blog_title}}</span> does not exist.
    </p>
    {% elif action == 2 %}
    <p class="alert alert-success">
        The blog post <span class="font-weight-bold">{{blog_title}}</span> was deleted successfully.
    </p>
    {% elif action == 3%}
    <p class="alert alert-success">
        The blog post <span class="font-weight-bold">{{blog_title}}</span> was changed successfully.
    </p>
    {% elif action == 4%}
    <p class="alert alert-success">
        The new comment was successfully added.
    </p>
    {% endif %}
</div>

src/try_django/blog/templates/blog/paginationbar.html
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">

        <!-- width = 34 -->
      {% ifequal page 1 %}
    <li class="page-item disabled">
        {% if not query %}
            <a class="page-link" href="/blog/{{ page|add:'-1' }}" tabindex="-1">Previous</a>
        {% else %}
            <a class="page-link" href="/blog/{{ page|add:'-1' }}/?q={{query}}" tabindex="-1">Previous</a>
        {% endif %}
    </li>
      {% else %}
      <li class="page-item">
        {% if not query %}
            <a class="page-link" href="/blog/{{ page|add:'-1' }}" tabindex="-1">Previous</a>
        {% else %}
            <a class="page-link" href="/blog/{{ page|add:'-1' }}/?q={{query}}" tabindex="-1">Previous</a>
        {% endif %}
    </li>
      {% endifequal %}

      {% for i in pages %}
        {% if i == page %}
            <li class="page-item active">
                {% if not query %}
                    <a class="page-link" href="/blog/{{i}}">{{i}}</a>
                {% else %}
                    <a class="page-link" href="/blog/{{i}}/?q={{query}}">{{i}}</a>
                {% endif %}
            </li>
        {% elif i == -1 %}
            <li class="page-link">...</li>
        {% else %}
            <li class="page-item">
                {% if not query %}
                    <a class="page-link" href="/blog/{{i}}">{{i}}</a>
                {% else %}
                    <a class="page-link" href="/blog/{{i}}/?q={{query}}">{{i}}</a>
                {% endif %}
            </li>
        {% endif %}
      {% endfor %}


      {% ifequal page last_page %}
    <li class="page-item disabled">
        {% if not query %}
            <a class="page-link" href="/blog/{{ page|add:'1' }}">Next</a>
        {% else %}
            <a class="page-link" href="/blog/{{ page|add:'1' }}/?q={{query}}">Next</a>
        {% endif %}
    </li>
      {% else %}
      <li class="page-item">
        {% if not query %}
            <a class="page-link" href="/blog/{{ page|add:'1' }}">Next</a>
        {% else %}
            <a class="page-link" href="/blog/{{ page|add:'1' }}/?q={{query}}">Next</a>
        {% endif %}
    </li>
      {% endifequal %}

  </ul>
</nav>

src/try_django/blog/templates/blog/toolbar.html
<div>
    <!--    <a href="javascript:history.back()"><span class="badge badge-light">&lt;&lt;</span></a> -->
    <a href="{{object.get_edit_url}}"><span class="badge badge-pill badge-warning text-dark">Edit</span></a>
    <a href="{{object.get_delete_url}}"><span class="badge badge-pill badge-danger text-dark">Delete</span></a>
</div>

src/try_django/blog/templates/blog/update.html
{% extends "base.html" %}

{% block content_b %}
<h3>{{object.title}} -- update</h3>
<p>{{object.content}}</p>
{% endblock %}